# Intel Integrated GPU Profile (Iris Xe/Arc Graphics)
# Optimized for Intel 11th Gen+ and Core Ultra processors

[server]
host = "0.0.0.0"
port = 8080
monitoring_port = 8081
max_connections = 10  # Limited connections

[models]
# Smallest models for iGPU constraints
whisper_model = "openai/whisper-tiny"  # 39M params only
whisper_precision = "int8"  # ~40MB
whisper_decoder_layers = 2  # Minimal layers
nllb_model = "facebook/nllb-200-distilled-600M"
nllb_precision = "int8"  # 450MB with CTranslate2
enable_ctranslate2 = true  # Essential for iGPU

# Disable accuracy features to save memory
enable_beam_search = false
temperature = 0.8
use_greedy = true

[streaming]
# Single stream only for iGPUs
max_concurrent_streams = 1
default_priority = "normal"
buffer_size = 256  # Minimal buffer
max_latency_ms = 500  # Realistic for iGPU

# Aggressive VAD to reduce processing
enable_vad = true
vad_threshold = 0.6  # Higher threshold
min_speech_duration_ms = 300
min_silence_duration_ms = 200
skip_silence = true
energy_threshold = 0.7  # Skip low energy audio

# Short chunks for responsiveness
chunk_duration_ms = 250  # 250ms chunks
chunk_overlap_ms = 50   # Minimal overlap
adaptive_chunking = false  # Too expensive

[cache]
# Minimal cache for memory savings
max_size_mb = 128
eviction_policy = "lru"
enable_compression = true
compression_level = 9  # Maximum compression
enable_warming = false  # No cache warming
kv_cache_precision = "int8"
max_context_tokens = 256  # Minimal context

[resources]
# Strict resource limits
max_cpu_percent = 50.0  # Leave room for GPU
max_memory_mb = 4096    # 4GB total
max_gpu_memory_mb = 2048  # 2GB for GPU
max_threads = 4
enable_dynamic_scaling = false

# Hybrid execution critical for iGPUs
enable_hybrid_execution = true
gpu_layers = 8   # Only 8 layers on GPU
cpu_layers = 24  # Rest on CPU
prefetch_layers = false  # Save memory

[optimization]
# Memory swapping essential
enable_model_swapping = true
swap_delay_ms = 50
keep_in_vram = ["embeddings"]  # Only embeddings stay

# No batching for lowest latency
max_batch_size = 1
batch_timeout_ms = 0

# Aggressive quantization
force_int8_quantization = true
dynamic_quantization = true
quantize_activations = true

[monitoring]
enable_metrics = false  # Disable to save resources
enable_tracing = false
enable_profiling = false
log_level = "warn"

[execution_providers]
# Intel-specific providers
providers = [
    "OpenVINOExecutionProvider",  # Best for Intel
    "DmlExecutionProvider",        # DirectML fallback
    "CPUExecutionProvider"
]

# OpenVINO settings for Intel iGPU
openvino_device_type = "GPU"
openvino_enable_fast_compile = true
openvino_num_threads = 4
openvino_cache_dir = "./openvino_cache"
openvino_throughput_streams = 1

# DirectML settings (Windows)
dml_device_filter = "GPU"
dml_performance_preference = "high_performance"

# CPU fallback settings
cpu_arena_extend_strategy = "kSameAsRequested"
enable_cpu_mem_arena = false  # Save memory

[quality_features]
# All disabled for performance
enable_punctuation = false
enable_truecasing = false
enable_speaker_diarization = false
enable_emotion_detection = false
enable_language_detection = false
filter_profanity = false

[power_management]
# Power efficiency settings
enable_power_throttling = true
target_power_watts = 28  # Typical iGPU power
enable_dynamic_frequency = true
prefer_efficiency_cores = false  # Use P-cores for GPU tasks